Repository HJYU16/study-board, pull requests merged in 2023-02, with the labels that each got.

#4 게시판 서비스 유즈케이스 작성
  document/use-case.svg
  use-case.svg
Labels: documentation

#6 스프링 부트 프로젝트 시작하기
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/fastcampus/studyboard/StudyBoardApplication.java
  src/main/resources/application.properties
  src/test/java/com/fastcampus/studyboard/StudyBoardApplicationTests.java
Labels: documentation

#8 도메인 설계
  document/board-erd.svg
  src/main/java/com/fastcampus/studyboard/domain/Article.java
  src/main/java/com/fastcampus/studyboard/domain/ArticleComment.java
  study-board.iml
Labels: documentation, enhancement

#10 데이터베이스 접근 로직 테스트 정의
  build.gradle
  document/board-erd.svg
  src/main/java/com/fastcampus/studyboard/config/JpaConfig.java
  src/main/java/com/fastcampus/studyboard/domain/Article.java
  src/main/java/com/fastcampus/studyboard/domain/ArticleComment.java
  src/main/java/com/fastcampus/studyboard/repository/ArticleCommentRepository.java
  src/main/java/com/fastcampus/studyboard/repository/ArticleRepository.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/fastcampus/studyboard/repository/JpaRepositoryTest.java
Labels: documentation, enhancement

#12 데이터베이스 접근 로직 구현
  src/main/java/com/fastcampus/studyboard/domain/Article.java
  src/main/java/com/fastcampus/studyboard/domain/ArticleComment.java
  src/main/java/com/fastcampus/studyboard/domain/BaseFields.java
  src/main/resources/application.yml
  study-board.iml
Labels: enhancement

#13 게시판 api 만들기 - Data REST 적용 및 테스트 정의
  build.gradle
  src/main/java/com/fastcampus/studyboard/repository/ArticleCommentRepository.java
  src/main/java/com/fastcampus/studyboard/repository/ArticleRepository.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/fastcampus/studyboard/controller/DataRestTest.java
  src/test/java/com/fastcampus/studyboard/repository/JpaRepositoryTest.java
Labels: enhancement

#14 게시판 api 만들기 - 구현까지 완료
  .gitignore
  build.gradle
  src/main/java/com/fastcampus/studyboard/repository/ArticleCommentRepository.java
  src/main/java/com/fastcampus/studyboard/repository/ArticleRepository.java
  src/test/java/com/fastcampus/studyboard/controller/DataRestTest.java
Labels: enhancement

#16 게시판 서비스 뷰 만들기
  build.gradle
  src/main/java/com/fastcampus/studyboard/StudyBoardApplication.java
  src/main/java/com/fastcampus/studyboard/config/SecurityConfig.java
  src/main/java/com/fastcampus/studyboard/config/ThymeleafConfig.java
  src/main/java/com/fastcampus/studyboard/controller/ArticleController.java
  src/main/java/com/fastcampus/studyboard/domain/Article.java
  src/main/java/com/fastcampus/studyboard/domain/ArticleComment.java
  src/main/java/com/fastcampus/studyboard/domain/BaseFields.java
  src/main/resources/application.yml
  src/main/resources/static/css/search-bar.css
  src/main/resources/templates/articles/detail.html
  src/main/resources/templates/articles/detail.th.xml
  src/main/resources/templates/articles/index.html
  src/main/resources/templates/articles/index.th.xml
  src/main/resources/templates/footer.html
  src/main/resources/templates/header.html
  src/main/resources/templates/index.html
  src/test/java/com/fastcampus/studyboard/controller/ArticleControllerTest.java
  src/test/java/com/fastcampus/studyboard/controller/AuthControllerTest.java
  study-board.iml
Labels: enhancement

#19 계정 도메인 추가 작업
  src/main/java/com/fastcampus/studyboard/domain/UserAccount.java
  src/main/java/com/fastcampus/studyboard/repository/UserAccountRepository.java
  src/main/resources/data.sql
  src/test/java/com/fastcampus/studyboard/controller/DataRestTest.java
Labels: enhancement

#21 도메인 수정 - 회원 계정과 게시글, 댓글 관계 연결
  src/main/java/com/fastcampus/studyboard/domain/Article.java
  src/main/java/com/fastcampus/studyboard/domain/ArticleComment.java
  src/test/java/com/fastcampus/studyboard/repository/JpaRepositoryTest.java
Labels: enhancement
